#include <iostream>

/*
	Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.`
*/

using namespace std;

int main()
{
	int sum = 0	
	,	fib1 = 0	
	,	fib2 = 1
	,	temp = 0;
	

	while(sum < 4000000)
	{		
		temp = fib2;
		fib2 = fib2 + fib1;
		fib1 = temp;
		if(fib2 % 2 == 0) 
		{
			sum += fib2;
			cout << fib2 << endl;
		}
	}	

	cout << endl;
	cout << endl;
	
	cout << sum << endl;

	return 0;
}


